### ISSUE TITLE
[vite-plugin-vue-type-imports] WARN: Cannot find type: Record

### ISSUE THREAD

**Issue by MingRock** [wheatjs/vite-plugin-vue-type-imports#32] opened 2022-09-15 04:47 UTC
When I upgrade from version 0.2.0 to version 0.2.2, I get an error

**Comment by Zolyn** [comment] 2022-09-15 05:08
Duplicate of #28 
See [Known limitations](https://github.com/wheatjs/vite-plugin-vue-type-imports/blob/main/README.md#known-limitations) and https://github.com/wheatjs/vite-plugin-vue-type-imports/issues/30#issuecomment-1245529537

**Comment by Zolyn** [comment] 2022-09-15 05:19
You can keep an eye on #28

**Closed as not planned by Zolyn** 2022-09-15 05:19 UTC
Labels: duplicate
